version: '3.8'

services:
  app:
    build:
      context: .
      target: production 
      args:
        DATABASE_URL: ${DATABASE_URL}
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      NODE_ENV: production
    volumes:
      - .:/usr/src/app # Map local files to the container for development
    command: >
      sh -c "prisma migrate deploy && node dist/app.js"

  app-dev:
    build:
      context: .
      target: development
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: >
      npm run dev
