import express from 'express';
import handleError from '../../helper/handleError';
import crypto from 'crypto';
import RazorPay from 'razorpay';
import * as dotenv from 'dotenv';

dotenv.config();

const paymentRouter = express.Router();

// Razorpay Configuration
const razorpay = new RazorPay({
  key_id: process.env.RAZORPAY_KEY_ID || 'rzp_test_xxx',
  key_secret: process.env.RAZORPAY_SECRET || 'xxx'
});


/**
 * @swagger
 * /payment:
 *   post:
 *     summary: Initiate a payment
 *     description: Creates a payment order with Razorpay for the specified amount.
 *     tags:
 *       - Payment
 *     security:
 *       - bearerAuth: []
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             properties:
 *               amount:
 *                 type: number
 *                 example: 2000
 *     responses:
 *       200:
 *         description: Payment created successfully.
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 id:
 *                   type: string
 *                   example: "pay_123"
 *                 amount:
 *                   type: number
 *                   example: 50000
 *                 currency:
 *                   type: string
 *                   example: "INR"
 *                 payment_capture:
 *                   type: boolean
 *                   example: true
 *       401:
 *         description: Authentication error.
 *       500:
 *         description: Internal server error.
 */
paymentRouter.post('/', async (req: any, res: any) => {
    try {
      const { amount } = req.body;
      const payment = await razorpay.orders.create({
        amount: amount,
        currency: 'INR',
        payment_capture: true
      });
      res.status(200).json(payment);
    } catch (error) {
      handleError(error, res);
    }
  });
  
  
  /**
 * @swagger
 * /payment/verify:
 *   post:
 *     summary: Verify payment using Razorpay payment details
 *     description: This endpoint verifies the payment by comparing the generated signature with the provided signature from Razorpay.
 *     tags:
 *       - Payment
 *     parameters:
 *       - in: body
 *         name: body
 *         required: true
 *         description: The details required to verify the payment.
 *         schema:
 *           type: object
 *           properties:
 *             order_id:
 *               type: string
 *               description: The unique order ID from Razorpay.
 *             payment_id:
 *               type: string
 *               description: The payment ID generated by Razorpay for the payment.
 *             signature:
 *               type: string
 *               description: The signature generated by Razorpay, used to verify the payment.
 *     responses:
 *       200:
 *         description: Payment successfully verified.
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 success:
 *                   type: boolean
 *                   description: Indicates if the payment verification was successful.
 *                 message:
 *                   type: string
 *                   description: Message indicating the verification result.
 *       400:
 *         description: Payment verification failed due to signature mismatch or other errors.
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 success:
 *                   type: boolean
 *                   description: Indicates if the payment verification failed.
 *                 message:
 *                   type: string
 *                   description: Message explaining the failure reason.
 *       500:
 *         description: Internal server error.
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 success:
 *                   type: boolean
 *                   description: Indicates that an error occurred during payment verification.
 *                 message:
 *                   type: string
 *                   description: Error message for internal issues.
 */

  paymentRouter.post('/verify', async (req: any, res: any) => {
    try {
      const { order_id, payment_id, signature } = req.body;
      const secret = process.env.RAZORPAY_SECRET || 'rzp_secret_xxx';
  
      const hmac = crypto.createHmac("sha256", secret)
      hmac.update(order_id + '|' + payment_id);
  
      const generatedSignature = hmac.digest("hex")
      
      if(generatedSignature === signature){
        res.status(200).json({
          success: true,
          message: "Payment verified!"
        });
      }
      res.status(400).json({
        success: false,
        message: "Payment not verified!"
      })
      
    } catch (error) {
      handleError(error, res);
    }
  });

export default paymentRouter;