-- AlterTable
ALTER TABLE "Order" ADD COLUMN     "addressId" INTEGER,
ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "storeName" TEXT NOT NULL DEFAULT 'null',
ADD COLUMN     "totalAmount" DOUBLE PRECISION NOT NULL DEFAULT 0.00,
ADD COLUMN     "vendorId" TEXT NOT NULL DEFAULT 'null';

-- AddForeignKey
ALTER TABLE "Order" ADD CONSTRAINT "Order_addressId_fkey" FOREIGN KEY ("addressId") REFERENCES "Address"("id") ON DELETE SET NULL ON UPDATE CASCADE;
