-- AlterTable
ALTER TABLE "Address" ADD COLUMN     "addressType" TEXT NOT NULL DEFAULT 'Home',
ADD COLUMN     "address_line1" TEXT NOT NULL DEFAULT 'NaN',
ADD COLUMN     "address_line2" TEXT NOT NULL DEFAULT 'NaN',
ADD COLUMN     "landmark" TEXT NOT NULL DEFAULT 'NaN',
ADD COLUMN     "latitude" DOUBLE PRECISION NOT NULL DEFAULT 0.00,
ADD COLUMN     "longitude" DOUBLE PRECISION NOT NULL DEFAULT 0.00;
